apiVersion: v1
kind: ConfigMap
metadata:
  name: app-configmap
data:
  SPRING_DATASOURCE_URL: "jdbc:mysql://db:3306/gestionevents"
  SPRING_DATASOURCE_USERNAME: "root"
  SPRING_DATASOURCE_PASSWORD: "rootpassword"
